### ISSUE TITLE
ds4 controller issues

### ISSUE THREAD

**Issue by johnblaze00** [FelixKratz/moonlight-mac#3]
hey

the app detects my ds4 controller but the controls are out of wack. x, cirlce square and triangle dont work. the left joystick works but l3 and r3 are mapped are l1 and l3. The official moonlight client for crhome its fine.

if you need anything else from me, let me know. more then happy to be a tester for you! the performance of this app is definitely better then the chrome one.

**Comment by FelixKratz** [comment]
This problem seems to arise because of the controller implementation. The mapping for the controller
has to be done manually at the moment, so no precomputing of the controller signal as it is possible in google chrome. The current mapping is for my DS3 controller. To fix this efficiently the controller implementation has to be rewritten from scratch. This is not a trivial fix, so this will take some time. But i will definitely be looking into this.

If anyone wants to try a manual mapping for the mean time you will have to edit the Control.m file to your needs.

**Comment by FelixKratz** [comment]
The DualShock 4 Controller is now the standard mapping and for all other controllers I have created a mapping tool.
